### ISSUE TITLE
Reply path under control of malicious client ?

### ISSUE THREAD

**Issue by WillCodeCo** [indra-labs/docs#1]
In the "Return Path Routing" section of the whitepaper I see this sentence:

`This is a limitation of source routing with anonymity, as the reply path is entirely under the control of the client.`

Does this have implications for when a malicious client communicates via Indra to some hidden service ? Can Eve choose a reply path that is exclusively made up of nodes she controls in order to de-anonymize Bob ?

Thanks !

**Comment by l0k18** [comment]
No, it is solved by both sides using a routing header. Either side can be malicious, but each side attaches their own routing header in front of the one provided by the other side, the sender only needs to put two hops in their layer to be secure though.

The work on this repo and the main `indra` repo is out of date. s7v2qgqpsgnak5rkrewh3gabd4h2hfluz7hpzr7mrtmscgb2pmzq2zqd.onion you can find the current work at this onion address.

**Comment by WillCodeCo** [comment]
I figured I must have misunderstood something, so that makes sense. Thank you for the clarification
